import { defineConfig } from "vitest/config";

export default defineConfig({
  resolve: { alias: [{ find: "preact/hooks", replacement: "react" }] },
  test: {
    environment: "node",
    globals: true,
    exclude: ["tests/ui/**", "tests/e2e/**", "node_modules/**", "dist/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      reportsDirectory: "coverage/sim",
      include: ["src/sim/**/*.ts"],
      exclude: ["src/sim/content/**", "src/sim/index.ts"],
      thresholds: {
        statements: 90,
        branches: 82,
        functions: 90,
        lines: 90,
        "src/sim/runtime-state.ts": { statements: 80, branches: 70, functions: 90, lines: 90 },
        "src/sim/runtime-random.ts": { statements: 90, branches: 90, functions: 90, lines: 90 },
        "src/sim/runtime-archive.ts": { statements: 95, branches: 80, functions: 95, lines: 95 },
        "src/sim/observation.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/sim/observation-access.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/sim/observation-identity.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/sim/knowledge-questions.ts": { statements: 90, branches: 80, functions: 90, lines: 90 },
        "src/sim/research-archive.ts": { statements: 85, branches: 75, functions: 90, lines: 90 },
        "src/sim/branching.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/branch-archive.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/branch-packages.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/branch-comparison.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/branch-replay.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/branch-inputs.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/constitution-validation.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/constitution-domain-validation.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/constitution-executor.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/constitution-comparison.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/runtime-topology.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/autonomy.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/autonomy-validation.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/runtime-causality-build.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
        "src/sim/runtime-causality-validation.ts": { statements: 90, branches: 82, functions: 90, lines: 90 },
      },
    },
  },
});
