import type { MiracleDefinition } from "../types";

export const miracleDefinitions: MiracleDefinition[] = [
  {
    type: "bless_planet",
    title: "祝福行星",
    targetKind: "planet",
    description: "向一颗行星注入稳定祝福，提高生命与文明出现后的韧性。",
    cost: {
      miraclePoints: 2,
      causalityStrain: 8,
      stabilityDelta: 3,
      lawPressureDelta: 1,
    },
    effect: {
      metric: "lifePotential",
      delta: 8,
      description: "行星祝福提高生命潜力，并让后续生命事件更容易扎根。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "life",
      delta: 12,
      explanation: "被祝福行星会提高后续生命纪元事件权重。",
    },
    longTermRisks: ["过度祝福会让局部生态依赖神迹，削弱自然演化韧性。"],
  },
  {
    type: "stabilize_star",
    title: "稳定恒星",
    targetKind: "star_system",
    description: "压制恒星异常波动，降低恒星系灾变概率。",
    cost: {
      miraclePoints: 2,
      causalityStrain: 7,
      stabilityDelta: 9,
      lawPressureDelta: 1,
    },
    effect: {
      metric: "stability",
      delta: 9,
      description: "恒星稳定术提高整体稳定度，并降低后续异常事件权重。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "anomaly",
      delta: -10,
      explanation: "稳定恒星会压低异常事件出现概率。",
    },
    longTermRisks: ["被强行稳定的恒星可能在遥远未来积累迟滞性爆发。"],
  },
  {
    type: "seed_life",
    title: "注入生命",
    targetKind: "planet",
    description: "在合适或边缘行星上播撒可演化生命火种。",
    cost: {
      miraclePoints: 3,
      causalityStrain: 12,
      stabilityDelta: -1,
      lawPressureDelta: 2,
    },
    effect: {
      metric: "lifePotential",
      delta: 13,
      description: "生命火种直接提高生命潜力，并推动后续生命事件。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "life",
      delta: 18,
      explanation: "被播撒生命的行星会显著提升生命事件权重。",
    },
    longTermRisks: ["外来生命火种可能与原生法则不兼容，引发生态断层。"],
  },
  {
    type: "grant_magic",
    title: "赐予魔法",
    targetKind: "civilization",
    description: "向文明开放受限魔法通道，改变其神话与技术路线。",
    cost: {
      miraclePoints: 3,
      causalityStrain: 14,
      stabilityDelta: -3,
      lawPressureDelta: 4,
    },
    effect: {
      metric: "magicIntensity",
      delta: 12,
      description: "赐予魔法提高魔法强度，并推动神话和异常事件权重。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "myth",
      delta: 14,
      explanation: "魔法赐予会提高神话纪元事件权重。",
    },
    longTermRisks: ["魔法通道会吸引神性实体或因果异常关注该文明。"],
  },
  {
    type: "send_catastrophe",
    title: "降下灾难",
    targetKind: "civilization",
    description: "对文明施加灾难压力，迫使其重组、衰亡或飞升。",
    cost: {
      miraclePoints: 2,
      causalityStrain: 16,
      stabilityDelta: -12,
      lawPressureDelta: 3,
    },
    effect: {
      metric: "stability",
      delta: -12,
      description: "灾难降低稳定度，并提高终局事件权重。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "ending",
      delta: 16,
      explanation: "灾难会提高终局或衰亡事件权重。",
    },
    longTermRisks: ["过度灾难会让文明把造物主识别为敌对神性。"],
  },
  {
    type: "revive_civilization",
    title: "复活文明",
    targetKind: "civilization",
    description: "从文明废墟或濒危状态中提取记忆火种，恢复延续机会。",
    cost: {
      miraclePoints: 4,
      causalityStrain: 18,
      stabilityDelta: -4,
      lawPressureDelta: 5,
    },
    effect: {
      metric: "civilizationPotential",
      delta: 15,
      description: "复活文明提高文明潜力，并让后续文明事件重新获得权重。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "civilization",
      delta: 18,
      explanation: "复活文明会提高后续文明事件权重。",
    },
    longTermRisks: ["被复活文明可能保留灭亡记忆，形成不稳定的神话债务。"],
  },
  {
    type: "seal_deity",
    title: "封印神明",
    targetKind: "mythology",
    description: "压制某个文明神话系统中的高影响神格。",
    cost: {
      miraclePoints: 4,
      causalityStrain: 17,
      stabilityDelta: 2,
      lawPressureDelta: 5,
    },
    effect: {
      metric: "divineActivity",
      delta: -13,
      description: "封印神明降低神性活跃，并改变神话事件走向。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "myth",
      delta: -12,
      explanation: "封印神明会压低神话事件权重。",
    },
    longTermRisks: ["神明封印可能在文明信仰中留下反噬性禁忌。"],
  },
  {
    type: "repair_causality",
    title: "修复因果裂缝",
    targetKind: "universe",
    description: "用奇迹点弥合法则裂缝，恢复宇宙级因果一致性。",
    cost: {
      miraclePoints: 5,
      causalityStrain: 20,
      stabilityDelta: 6,
      lawPressureDelta: -8,
    },
    effect: {
      metric: "causalityIntegrity",
      delta: 16,
      description: "修复因果裂缝提高因果完整度，并降低异常事件权重。",
      influence: "metric",
      affectsFuture: true,
    },
    probabilityShift: {
      eventType: "anomaly",
      delta: -18,
      explanation: "修复因果裂缝会显著压低异常事件权重。",
    },
    longTermRisks: ["大规模修复会暴露造物主干预痕迹，引发更高层法则校验。"],
  },
];
